### ISSUE TITLE
Basic RAG Guide typo/mismatch

### ISSUE THREAD

**Issue by avriiil** [mistralai/cookbook#17]
While working through the basic RAG guide I discovered a mismatch between the code on Colab and the code on the website. 

Website:
<img width="792" alt="image" src="https://github.com/mistralai/cookbook/assets/68642378/87c169d4-7cb4-46a8-8df2-0998b106fc8a">

Colab:
<img width="768" alt="image" src="https://github.com/mistralai/cookbook/assets/68642378/830a951f-fedd-4c5c-b592-0336edca66ae">

**Comment by sophiamyang** [comment]
fixed. thanks!
