### ISSUE TITLE
is it possible lower the codestral to 7B or small model?

### ISSUE THREAD

**Issue by code959437957** [mistralai/cookbook#41]
is it possible lower the codestral to 7B or small model?
my laptop not able to running codestral model with 22B size.

**Comment by pandora-s-git** [comment]
Hi, the best option for those cases is to go for Quantization, a different method would be distillation but it's a very expensive process (basically making a new model) so your best option for now would be to go for a Quant, feel free to join our discord to discuss this. I will be closing this issue if that's okay!
